title: Engineers
modelClass: OpenMindedIT\FieldEngineeringToolkit\Models\Engineers
list: $/openmindedit/fieldengineeringtoolkit/models/engineers/columns.yaml
recordUrl: 'openmindedit/fieldengineeringtoolkit/engineers/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
