title: Visits
modelClass: OpenMindedIT\FieldEngineeringToolkit\Models\Visits
list: $/openmindedit/fieldengineeringtoolkit/models/visits/columns.yaml
recordUrl: 'openmindedit/fieldengineeringtoolkit/visits/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
