title: Modems
modelClass: OpenMindedIT\FieldEngineeringToolkit\Models\Modems
list: $/openmindedit/fieldengineeringtoolkit/models/modems/columns.yaml
recordUrl: 'openmindedit/fieldengineeringtoolkit/modems/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 100
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
