title: Customers
modelClass: OpenMindedIT\FieldEngineeringToolkit\Models\Customers
list: $/openmindedit/fieldengineeringtoolkit/models/customers/columns.yaml
recordUrl: 'openmindedit/fieldengineeringtoolkit/customers/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
