title: Todo
modelClass: OpenMindedIT\FieldEngineeringToolkit\Models\Todo
list: $/openmindedit/fieldengineeringtoolkit/models/todo/columns.yaml
recordUrl: 'openmindedit/fieldengineeringtoolkit/todo/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
