title: Planning
modelClass: OpenMindedIT\FieldEngineeringToolkit\Models\Planning
list: $/openmindedit/fieldengineeringtoolkit/models/planning/columns.yaml
recordUrl: 'openmindedit/fieldengineeringtoolkit/planning/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
